# ref: https://docs.docker.com/compose/compose-file/
version: "3"

services:
  #WEB APP
  web:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - mybridge_network
  #API
  api:
    build: ./backend
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "000000"
      POSTGRES_DB: "pegasus"
      DATABASE_URL: postgres://postgres@domain.com:000000@phttp://127.0.0.1:5432/pegasus
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - mybridge_network
    command: npx nodemon index.js
  # Database
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./sql_script/init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "pegasus"
    networks:
      - mybridge_network
    #command: ["sleep", "999"]
    #command: ./docker-entrypoint-initdb.d/init.sql

  # pgadmin4
  pg4:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "000000"
    networks:
      - mybridge_network

networks:
  mybridge_network:

volumes:
  pgdata:
# version: "3.8"

# #database
# services:
#   db:
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: "000000"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - mybridge_network

#   #pgadmin4
#   pg4:
#     depends_on:
#       - db
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - "8080:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "user@domain.com"
#       PGADMIN_DEFAULT_PASSWORD: "000000"
#     networks:
#       - mybridge_network

#   networks:
#     mybridge_network:

#   volumes:
#     pgdata:
# #docker run -p 80:80 --name pg4_2 -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' -e 'PGADMIN_DEFAULT_PASSWORD=000000' -d dpage/pgadmin4
# #docker run --name postgres_db2 -e POSTGRES_PASSWORD=000000 -d -p 5432:5432 -v pgdata:/var/lib/postgresql/data postgres
