# ref: https://docs.docker.com/compose/compose-file/
version: "3"

services:
  # Database
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: always
    # env_file:
    #   - ./backend/.env
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= pass
      - POSTGRES_DB= db
    networks:
      - mybridge_network
  #WEB APP
  # web:
  #   build: ./frontend
  #   ports:
  #     - "8080:3000"
  #   networks:
  #     - mybridge_network
  #API
  api:
    depends_on:
      - postgres
    build: ./backend
    environment:
      - NODE_ENV=development

    # env_file:
    #   - ./backend/.env

    networks:
      - mybridge_network
    # command: npm start

    #command: ["sleep", "999"]
    #command: ./docker-entrypoint-initdb.d/init.sql

  # pgadmin4
  # pg4:
  #   depends_on:
  #     - db
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "postgres@domain.com"
  #     PGADMIN_DEFAULT_PASSWORD: "000000"
  #   networks:
  #     - mybridge_network

networks:
  mybridge_network:

volumes:
  pgdata:
